# Generated by Django 4.1.1 on 2022-09-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MusicPlayer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "Nome",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("Cognome", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="genere",
            fields=[
                (
                    "Nome",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AddField(
            model_name="song",
            name="PathSong",
            field=models.CharField(default="null", max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "Nome",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("TrackNumer", models.IntegerField()),
                ("release_date", models.DateField()),
                ("PathIMM", models.CharField(max_length=200)),
                (
                    "Artista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MusicPlayer.artist",
                    ),
                ),
                (
                    "genere",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="MusicPlayer.genere",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="song",
            name="Album",
            field=models.ForeignKey(
                default="singolo",
                on_delete=django.db.models.deletion.CASCADE,
                to="MusicPlayer.album",
            ),
        ),
        migrations.AddField(
            model_name="song",
            name="Artista",
            field=models.ForeignKey(
                default="null",
                on_delete=django.db.models.deletion.CASCADE,
                to="MusicPlayer.artist",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="song",
            name="genere",
            field=models.ForeignKey(
                default="indie",
                on_delete=django.db.models.deletion.CASCADE,
                to="MusicPlayer.genere",
            ),
        ),
    ]
